macro (my_add_target name type)
    # 用法: my_add_target(pybmain EXECUTABLE biology otherdeps)
    file(GLOB_RECURSE srcs CONFIGURE_DEPENDS src/*.cpp src/*.h)
    if ("${type}" MATCHES "EXECUTABLE")
        add_library(${name} ${type} ${srcs})
    else()
        add_executable(${name} ${srcs})
    endif()
    list(SUBLIST ${ARGV} 2 -1 links)
    target_link_libraries(${name} PUBLIC ${links})
    target_include_directories(${name} PUBLIC include)
endmacro()
